name: Evaluate performance

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        required: true
        default: '3.x'
        description: 'Python version to use'

jobs:
  performance:
    name: Evaluate performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r ./requirements.txt -r ./requirements-jupyter.txt
      - name: Install package
        run: pip install .
      - name: Execute notebook
        run: jupyter nbconvert --to notebook --debug --execute --inplace ./notebooks/overhead.ipynb
      - name: Stage changes
        run: |
          git add ./notebooks/*
          git add ./performance/*
      - name: Commit changes
        run: git commit -m "Update performance evaluation"
      - name: Push changes
        run: git push