name: Test pull request

on:
  pull_request:

jobs:
  code_style:
    name: Code style
    uses: './.github/workflows/code_style.yml'
  unit_tests:
    name: Unit tests
    needs: code_style
    uses: './.github/workflows/unit_tests.yml'
    with:
      testing: true